name: Deploy Svelte to GitHub Pages

on:
  push:
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with: { version: latest }
      - uses: actions/setup-node@v3
        with:
          node-version: '*'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - run: pnpm run build
      - uses: actions/upload-pages-artifact@v1
        with: { path: dist }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
